//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhulikhelSHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DhulikhelDBEntities : DbContext
    {
        public DhulikhelDBEntities()
            : base("name=DhulikhelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WardBhela> WardBhelas { get; set; }
        public virtual DbSet<WBCategory> WBCategories { get; set; }
        public virtual DbSet<WBPlan> WBPlans { get; set; }
    }
}
