//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhulikhelSHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardBhela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WardBhela()
        {
            this.WBPlans = new HashSet<WBPlan>();
        }
    
        public int WardBhelaID { get; set; }
        public Nullable<System.DateTime> WardBhelaDate { get; set; }
        public string WardNumber { get; set; }
        public Nullable<int> PresentMale { get; set; }
        public Nullable<int> PresentFemale { get; set; }
        public Nullable<int> PresentBoy { get; set; }
        public Nullable<int> PresentGirl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WBPlan> WBPlans { get; set; }
    }
}
